chassis:
  x:
    pid: { p: 17.0, i: 0.0, d: 15.0, i_clamp_max: 0.1, i_clamp_min: -0.1, antiwindup: true, publish_state: true }
  y:
    pid: { p: 17.0, i: 0.0, d: 15.0, i_clamp_max: 0.1, i_clamp_min: -0.1, antiwindup: true, publish_state: true }