chassis:
  x:
    pid: { p: 9.0, i: 0.0, d: 10.0, i_clamp_max: 0.1, i_clamp_min: -0.1, antiwindup: true, publish_state: true }
  y:
    pid: { p: 9.0, i: 0.0, d: 10.0, i_clamp_max: 0.1, i_clamp_min: -0.1, antiwindup: true, publish_state: true }
  yaw:
    pid: { p: 10.0, i: 0.0, d: 0.0, i_clamp_max: 0.1, i_clamp_min: -0.1, antiwindup: true, publish_state: true }
