steps:

  - step: top
    end_effector_target:
      frame: base_link
      position: [ 0.4, 0.0, 0.3 ]
      rpy: [ 0., 1.5707, 0. ]

  - step: approach
    end_effector_target:
      frame: base_link
      position: [ 0.4, 0.0, 0.1 ]
      rpy: [ 0., 1.5707, 0. ]

  - step: 3
    end_effector_target:
      frame: base_link
      position: [ 0.4, 0.0, 0.3 ]
      rpy: [ 0., 1.5707, 0. ]

  - step: 4 # number is unnecessary
    end_effector_target:
      frame: base_link
      position: [ 0.0, 0.0, 0.4 ]
      rpy: [ 0., -3.1415926, 0. ]
