steps:
  - step: 1 # number is unnecessary
    end_effector_target:
      hand_open: before
      frame: base_link
      position: [ 0.4, 0.0, 0.3 ]
      rpy: [ 0., 1.5707, 0. ]
  - step: 2 # number is unnecessary
    end_effector_target:
      hand_close: after
      frame: base_link
      position: [ 0.4, 0.0, 0.1 ]
      rpy: [ 0., 1.5707, 0. ]
  - step: 3 # number is unnecessary
    end_effector_target:
      frame: base_link
      position: [ 0.4, 0.0, 0.3 ]
      rpy: [ 0., 1.5707, 0. ]
  - step: 4 # number is unnecessary
    end_effector_target:
      hand_open: after
      frame: base_link
      position: [ 0.0, 0.0, 0.4 ]
      rpy: [ 0., -3.1415926, 0. ]
