steps:
  - step: grasp
    end_effector_target:
      hand_open: after

  - step: top
    end_effector_target:
      frame: base_link
      position: [ 0.45, 0.0, 0.3 ]
      rpy: [ 0., 1.5707, 0. ]

  - step: approach
    end_effector_target:
      frame: base_link
      position: [ 0.45, 0.0, 0.05 ]
      rpy: [ 0., 1.5707, 0.07 ]
      cartesian: true

  - step: grasp
    end_effector_target:
      hand_close: after

  - step: 3
    end_effector_target:
      frame: base_link
      position: [ 0.47, 0.0, 0.3 ]
      rpy: [ 0., 1.5707, 0. ]

  - step: 4 # number is unnecessary
    end_effector_target:
      frame: base_link
      position: [ 0.1, 0.0, 0.4 ]
      rpy: [ 0., -3.1415926, 0. ]

  - step: grasp
    end_effector_target:
      hand_open: after
