scences_list:
  Island:
    - id: "big"
      frame_id: "base_link"
      primitive:
        type: box
        dimension: [ 0.1, 0.3, 0.1 ]
      pose:
        position: [ 0., 0., 0.5 ]
        orientation: [0., 0., 0., 0.]
