scences_list:
  TEST_BOX:
    - id: "big"
      frame_id: "base_link"
      primitive:
        type: box
        dimension: [ 0.1, 0.3, 0.1 ]
      pose:
        position: [ 0., 0., 1.5 ]
        orientation: [ 0., 0., 0., 0. ]
  TEST_CONE:
    - id: "big1"
      frame_id: "base_link"
      primitive:
        type: cone
        dimension: [ 0.1, 0.3 ]
      pose:
        position: [ 0., 0., 1.5 ]
        orientation: [ 0., 0., 0., 0. ]
  TEST_CYLINDER:
    - id: "big2"
      frame_id: "base_link"
      primitive:
        type: cylinder
        dimension: [ 0.1, 0.3 ]
      pose:
        position: [ 0., 0., 1.5 ]
        orientation: [ 0., 0., 0., 0. ]
  TEST_SPHERE:
    - id: "big3"
      frame_id: "base_link"
      primitive:
        type: sphere
        dimension: [ 0.1 ]
      pose:
        position: [ 0., 0., 1.5 ]
        orientation: [ 0., 0., 0., 0. ]
