scences_list:
  Island:
    - id: "big"
      frame_id: "base_link"
      primitive:
        type: box
        dimension: [ 1.5, 1.1, 1.48 ]
      pose:
        position: [0., 0., 0.]
        orientation: [0., 0., 0., 0.]
    - id: "big1"
      frame_id: "base_link"
      primitive:
        type: box
        dimension: [ 1.5, 1.1, 1.48 ]
      pose:
        position: [2.4, 0.4, 0.4]
        orientation: [0., 0., 0., 0.]