common:
  slowly: &slowly
    speed: 0.2
    accel: 0.2
    timeout: 5
  quickly: &quickly
    speed: 1.0
    accel: 1.0
    timeout: 2
  hand_open: &hand_open
    joints: [ 0. ]
    <<: *quickly
    tolerance_angular: 0.01
  hand_close: &hand_close
    joints: [ -0.028 ]
    <<: *quickly
    tolerance_angular: 0.05
  arm_home: &arm_home
    joints: [ 0., -2.181, 2.164, 0.0, 0.0 ]
    <<: *quickly
  arm_fold: &arm_fold
    joints: [ -2.87, -0.22, 0.62, 0.26, 0.0 ]
    <<: *quickly

steps_list:
  ARM_TEST: # ARM_TEST
    - step: hand_open
      hand:
        <<: *hand_open
    - step: home
      arm:
        <<: *arm_home
        <<: *quickly
        tolerance_angular: 0.2
    - step: fold
      arm: *arm_fold
      tolerance_angular: 0.1
    - step: close_hand
      hand: *hand_close