common:
  slowly: &SLOWLY
    speed: 0.2
    accel: 0.2
    timeout: 5.
  quickly: &QUICKLY
    speed: 1.0
    accel: 0.7
    timeout: 2.
  hand_open: &HAND_OPEN
    position: 0.
    delay: 0.1
  hand_close: &HAND_CLOSE
    position: -0.026
    delay: 0.4
  arm_home: &ARM_HOME
    joints: [ 0., -2.181, 2.164, 0.0, 0.0 ]
    <<: *QUICKLY
    tolerance_angular: 0.1
  arm_fold_lower: &ARM_FOLD_LOWER
    joints: [ -2.65, -0.22, 0.62, 0.26, 0.0 ]
    <<: *QUICKLY
    tolerance_angular: 0.5
  arm_fold_upper: &ARM_FOLD_UPPER
    joints: [ -2.65, -1.239, 1.01, 0.26, 0.0 ]
    <<: *QUICKLY
    tolerance_angular: 0.5

steps_list:
  ARM_TEST: # ARM_TEST
    - step: "open_hand"
      hand: *HAND_OPEN
    - step: "home"
      arm:
        <<: *ARM_HOME
        <<: *SLOWLY
    - step: "fold_lower"
      arm: *ARM_FOLD_LOWER
    - step: "close_hand"
      hand: *HAND_CLOSE
  ARM_FOLD_LOWER:
    - step: "fold_lower"
      arm: *ARM_FOLD_LOWER
  GRASP_BIG:
    - step: "hand_open"
      hand: *HAND_OPEN
    - step: "fold_upper"
      arm: *ARM_FOLD_UPPER
    - step: "home"
      arm: *ARM_HOME
    - step: "approach"
      arm:
        frame: base_link
        position: [ 0.5, 0., 0.48 ]
        rpy: [ 0., 0.124, 0. ]
        <<: *QUICKLY
        tolerance_linear: 0.001
        tolerance_angular: 0.001
    - step: "close_hand"
      hand: *HAND_CLOSE
    - step: "pull_up"
      arm:
        frame: base_link
        position: [ 0.3, 0., 0.65 ]
        rpy: [ 0., -0.7866, 0. ]
        <<: *QUICKLY
        tolerance_linear: 0.001
        tolerance_angular: 0.001
    - step: "fold_upper"
      arm: *ARM_FOLD_UPPER
    - step: "fold_lower"
      arm: *ARM_FOLD_LOWER
  GRASP_SMALL:
    - step: "hand_open"
      hand: *HAND_OPEN
    - step: "turn"
      arm:
        joints: [ -2.735, -1.452, -0.133, 1.06, 0.0125 ]
        <<: *QUICKLY
        tolerance_angular: 0.1
    - step: "turn"
      arm:
        frame: base_link
        position: [ 0.226, 0., 0.65 ]
        rpy: [ 0., -0.5259, 0. ]
        <<: *QUICKLY
        tolerance_linear: 0.001
        tolerance_angular: 0.001
    - step: "forward"
      chassis:
        frame: base_link
        position: [ 0.3, 0. ]
        yaw: 0.0
        tolerance_linear: 0.1
        tolerance_angular: 0.01
    - step: "approach"
      arm:
        frame: base_link
        position: [ 0.262, 0., 0.62 ]
        rpy: [ 0., 0., 0. ]
        <<: *QUICKLY
        tolerance_linear: 0.001
        tolerance_angular: 0.001
    - step: "close_hand"
      hand: *HAND_CLOSE
    - step: "rise"
      arm:
        frame: base_link
        position: [ 0.226, 0., 0.65 ]
        rpy: [ 0., -0.5259, 0. ]
        <<: *QUICKLY
        tolerance_linear: 0.01
        tolerance_angular: 0.001
    - step: "turn"
      arm:
        joints: [ -2.735, -1.452, -0.133, 1.06, 0.0125 ]
        <<: *QUICKLY
        tolerance_angular: 0.1

  PLACE:
    - step: "backward"
      chassis:
        frame: base_link
        position: [ -0.3, 0. ]
        yaw: 0.0
        tolerance_linear: 0.02
        tolerance_angular: 0.01
        timeout: 2.0
    - step: "fold_upper"
      arm: *ARM_FOLD_UPPER
    - step: "rise_up"
      arm:
        frame: base_link
        position: [ 0.24, 0., 0.65 ]
        rpy: [ 0., -0.474, 0. ]
        <<: *QUICKLY
        tolerance_linear: 0.01
        tolerance_angular: 0.001
    - step: "forward"
      chassis:
        frame: base_link
        position: [ 0.4, 0. ]
        yaw: 0.0
        tolerance_linear: 0.10
        tolerance_angular: 0.01
        timeout: 5.0
    - step: "open_hand"
      hand: *HAND_OPEN
    - step: "backward"
      chassis:
        frame: base_link
        position: [ -0.3, 0. ]
        yaw: 0.0
        tolerance_linear: 0.1
        tolerance_angular: 0.01
        timeout: 2.0
      arm:
        frame: base_link
        position: [ 0.188, 0., 0.60 ]
        rpy: [ 0., -0.170, 0. ]
        <<: *QUICKLY
        tolerance_linear: 0.01
        tolerance_angular: 0.001
    - step: "close_hand"
      hand: *HAND_CLOSE
    - step: "push"
      chassis:
        frame: base_link
        position: [ 0.4, 0. ]
        yaw: 0.0
        tolerance_linear: 0.2
        tolerance_angular: 0.1
        timeout: 2.0
      arm:
        frame: base_link
        position: [ 0.35, 0., 0.62 ]
        rpy: [ 0., -0.127, 0. ]
        <<: *QUICKLY
        tolerance_linear: 0.1
        tolerance_angular: 0.5
    - step: "backward"
      chassis:
        frame: base_link
        position: [ -0.3, 0. ]
        yaw: 0.0
        tolerance_linear: 0.1
        tolerance_angular: 0.01
        timeout: 2.0
    - step: "fold_lower"
      arm: *ARM_FOLD_LOWER