common:
  slowly: &SLOWLY
    speed: 0.2
    accel: 0.2
    timeout: 10
  normally: &NORMALLY
    speed: 0.5
    accel: 0.5
    timeout: 6.
  quickly: &QUICKLY
    speed: 1.
    accel: 1.
    timeout: 4.

  open_gripper: &OPEN_GRIPPER
    state: false
  close_gripper: &CLOSE_GRIPPER
    state: true

  normal_tolerance: &NORMAL_TOLERANCE
    tolerance_joints: [ 0.009, 0.009, 0.009, 0.006, 0.1, 0.1, 0.1 ]
  bigger_tolerance: &BIGGER_TOLERANCE
    tolerance_joints: [ 0.014, 0.02, 0.02, 0.009, 0.2, 0.2, 0.2 ]

  arm:
    home: &ARM_HOME
      joints: [ 0.012, 0., 0.218, 0., 0.87, 0., 0. ]
      <<: *NORMALLY
      <<: *NORMAL_TOLERANCE
    home_store: &ARM_HOME_STORE
      joints: [ 0.17, -0.063, 0.213, 0., 1.0266, 0., 0. ]
      <<: *NORMALLY
      <<: *BIGGER_TOLERANCE

  gimbal:
    grasp_stone: &SKY_POS
      frame: gimbal_base
      position: [ -0.2, -0.0008, 1 ]
    sky_pos: &BIG_STONE_POS
      frame: gimbal_base
      position: [ 31, 0, 0.1 ]
    walking_pos: &WALKING_POS
      frame: gimbal_base
      position: [ 0.1 ,0, -0.9 ]
    back_pos: &BACK_POS
      frame: gimbal_base
      position: [ -2 ,-0.1, -15 ]

steps_list:
  ################### COMMON ####################
  SKY_GIMBAL:
    - step: "open gripper"
      gimbal:
        <<: *SKY_POS

  WALKING_GIMBAL:
    - step: "open gripper"
      gimbal:
        <<: *WALKING_POS

  BIG_GIMBAL:
    - step: "open gripper"
      gimbal:
        <<: *BIG_STONE_POS

  OPEN_GRIPPER:
    - step: "open gripper"
      gripper:
        <<: *OPEN_GRIPPER

  CLOSE_GRIPPER:
    - step: "close gripper"
      gripper:
        <<: *CLOSE_GRIPPER

  BACK_HOME:
    - step: "approach"
      arm:
        <<: *ARM_HOME
  BACK_HOME_STORE:
    - step: "back home"
      arm:
        <<: *ARM_HOME_STORE

  DELETE_SCENE:
    - step: "delete_scene"

  LOOK_BACK:
    - step: "look back"

  BIG_STONE_POS_GIMBAL:
    - step: "gimbal"
      gimbal:
        <<: *BIG_STONE_POS

  WALKING_POS_GIMBAL:
    - step: "gimbal"
      gimbal:
        <<: *WALKING_POS

  SKY_POS_GIMBAL:
    - step: "gimbal"
      gimbal:
        <<: *SKY_POS

  WALKING_STONE:
    - step: "change"
      arm:
        joints: [ 0.002, -0.149, 0.097, 0., 1.566, 0., 0. ]
        <<: *SLOWLY
        <<: *NORMALLY

  BACK_POS:
    - step: "gimbal"
      gimbal:
        <<: *BACK_POS

  ################### BIG_ISLAND ####################
  ###################    MID    ####################
  MID_BIG_ISLAND0:
    - step: "add scene of sky island"
      scene_name: "BIG_STONE_ISLAND"
    - step: "gimbal"
      gimbal:
        <<: *BIG_STONE_POS
    - step: "move to mid ready"
      arm:
        frame: base_link
        position: [ 0.58598, 0.00055, 0.59362 ]
        rpy: [ 3.13816, 1.25975, 3.13714 ]
        <<: *QUICKLY
        tolerance_linear: 0.001

  MID_BIG_ISLAND00:
    - step: "add scene of sky island"
      scene_name: "BIG_STONE_ISLAND"
    - step: " gripper"
      gripper:
        <<: *OPEN_GRIPPER
    - step: "move to mid ready"
      arm:
        frame: base_link
        position: [ 0.58598, 0.00055, 0.59362 ]
        rpy: [ 3.13816, 1.25975, 3.13714 ]
        <<: *QUICKLY
        tolerance_linear: 0.001
    - step: "move to mid repeat"
      arm:
        joints: [ 0.235, 0.32, 0.3, 0., 1.88, 0., 0. ]
        <<: *NORMALLY
        <<: *NORMAL_TOLERANCE
    - step: "forward to catch stone"
      arm:
        joints: [ 0.235, 0.284, 0.277, 0,1.22, 0, 0 ]
        <<: *SLOWLY
        <<: *NORMAL_TOLERANCE

  MID_BIG_ISLAND000:
    - step: "add scene of sky island"
      scene_name: "BIG_STONE_ISLAND"
    - step: "gimbal"
      gimbal:
        <<: *WALKING_POS
    - step: "move to mid ready"
      arm:
        <<: *ARM_HOME

  ###################    LF    ####################
  LF_BIG_ISLAND0:
    - step: "add scene of sky island"
      scene_name: "BIG_STONE_ISLAND"
    - step: "gimbal"
      gimbal:
        <<: *BIG_STONE_POS
    - step: "move to mid ready"
      arm:
        frame: base_link
        position: [ 0.58598, 0.2988, 0.59362 ]
        rpy: [ 3.13816, 1.25975, 3.13714 ]
        <<: *QUICKLY
        tolerance_linear: 0.001

  LF_BIG_ISLAND00:
    - step: "add scene of sky island"
      scene_name: "BIG_STONE_ISLAND"
    - step: " gripper"
      gripper:
        <<: *OPEN_GRIPPER
    - step: "move to mid ready"
      arm:
        frame: base_link
        position: [ 0.58598, 0.2988, 0.59362 ]
        rpy: [ 3.13816, 1.25975, 3.13714 ]
        <<: *QUICKLY
        tolerance_linear: 0.001
    - step: "move to mid repeat"
      arm:
        joints: [ 0.235, 0.32, 0.3, 0.3, 1.88, 0., 0. ]
        <<: *NORMALLY
        <<: *NORMAL_TOLERANCE
    - step: "forward to catch stone"
      arm:
        joints: [ 0.235, 0.284, 0.277, 0.3,1.22, 0, 0 ]
        <<: *SLOWLY
        <<: *NORMAL_TOLERANCE

  LF_BIG_ISLAND000:
    - step: "add scene of sky island"
      scene_name: "BIG_STONE_ISLAND"
    - step: "gimbal"
      gimbal:
        <<: *WALKING_POS
    - step: "move to mid ready"
      arm:
        <<: *ARM_HOME

  ###################    RT    ####################
  RT_BIG_ISLAND0:
    - step: "add scene of sky island"
      scene_name: "BIG_STONE_ISLAND"
    - step: "gimbal"
      gimbal:
        <<: *BIG_STONE_POS
    - step: "move to mid ready"
      arm:
        frame: base_link
        position: [ 0.58598, -0.2988, 0.59362 ]
        rpy: [ 3.13816, 1.25975, 3.13714 ]
        <<: *QUICKLY
        tolerance_linear: 0.001

  RT_BIG_ISLAND00:
    - step: "add scene of sky island"
      scene_name: "BIG_STONE_ISLAND"
    - step: " gripper"
      gripper:
        <<: *OPEN_GRIPPER
    - step: "move to mid ready"
      arm:
        frame: base_link
        position: [ 0.58598, -0.2988, 0.59362 ]
        rpy: [ 3.13816, 1.25975, 3.13714 ]
        <<: *QUICKLY
        tolerance_linear: 0.001
    - step: "move to mid repeat"
      arm:
        joints: [ 0.235, 0.32, 0.3, -0.3, 1.88, 0., 0. ]
        <<: *NORMALLY
        <<: *NORMAL_TOLERANCE
    - step: "forward to catch stone"
      arm:
        joints: [ 0.235, 0.284, 0.277, -0.3,1.22, 0, 0 ]
        <<: *SLOWLY
        <<: *NORMAL_TOLERANCE

  RT_BIG_ISLAND000:
    - step: "add scene of sky island"
      scene_name: "BIG_STONE_ISLAND"
    - step: "gimbal"
      gimbal:
        <<: *WALKING_POS
    - step: "move to mid ready"
      arm:
        <<: *ARM_HOME

  ###################    READY    ####################
  READY_BIG_ISLAND0:
    - step: ""

  ###################    SKY_ISLAND    ####################
  ###################    MID    ####################
  MID_SKY_ISLAND0:
    - step: "add scene of sky island"
      scene_name: "SKY_STONE_ISLAND"
    - step: "move gimbal toward to island"
      gimbal:
        <<: *BACK_POS
    - step: "move to ready sky"
      arm:
        frame: base_link
        position: [ -0.29, -0.001, 0.9232 ]
        rpy: [ -0.0035, -0.0997, 3.1357968 ]
        <<: *NORMALLY
        tolerance_linear: 0.001

  MID_SKY_ISLAND00:
    - step: "add scene of sky island"
      scene_name: "SKY_STONE_ISLAND"
    - step: "open gripper to grasp stone"
      gripper:
        <<: *OPEN_GRIPPER
    - step: "move to ready sky"
      arm:
        frame: base_link
        position: [ -0.29, -0.001, 0.9232 ]
        rpy: [ -0.0035, -0.0997, 3.1357968 ]
        <<: *NORMALLY
        tolerance_linear: 0.001
    - step: "forward to catch stone"
      arm:
        joints: [ 0.2313, -0.33, -0.11, 0,0.2189, 0.002, 3.13 ]
        <<: *NORMALLY
        <<: *NORMAL_TOLERANCE

  MID_SKY_ISLAND000:
    - step: "add scene of sky island"
      scene_name: "SKY_STONE_ISLAND"
    - step: "move gimbal to toward"
      gimbal:
        <<: *WALKING_POS
    - step: "move to mid ready"
      arm:
        <<: *ARM_HOME

  ###################    LF    ####################
  LF_SKY_ISLAND0:
    - step: "add scene of sky island"
      scene_name: "SKY_STONE_ISLAND"
    - step: "move gimbal toward to island"
      gimbal:
        <<: *BACK_POS
    - step: "move to ready sky"
      arm:
        frame: base_link
        position: [ -0.29, -0.2988, 0.9232 ]
        rpy: [ -0.0035, -0.0997, 3.1357968 ]
        <<: *NORMALLY
        tolerance_linear: 0.001

  LF_SKY_ISLAND00:
    - step: "add scene of sky island"
      scene_name: "SKY_STONE_ISLAND"
    - step: "open gripper to grasp stone"
      gripper:
        <<: *OPEN_GRIPPER
    - step: "move to ready sky"
      arm:
        frame: base_link
        position: [ -0.29, -0.2988, 0.9232 ]
        rpy: [ -0.0035, -0.0997, 3.1357968 ]
        <<: *NORMALLY
        tolerance_linear: 0.001
    - step: "forward to catch stone"
      arm:
        joints: [ 0.2313, -0.33, -0.11, -0.3,0.2189, 0.002, 3.13 ]
        <<: *NORMALLY
        <<: *NORMAL_TOLERANCE

  LF_SKY_ISLAND000:
    - step: "add scene of sky island"
      scene_name: "SKY_STONE_ISLAND"
    - step: "move gimbal to toward"
      gimbal:
        <<: *WALKING_POS
    - step: "move to mid ready"
      arm:
        <<: *ARM_HOME

  ###################    RT    ####################
  RT_SKY_ISLAND0:
    - step: "add scene of sky island"
      scene_name: "SKY_STONE_ISLAND"
    - step: "move gimbal toward to island"
      gimbal:
        <<: *BACK_POS
    - step: "move to ready sky"
      arm:
        frame: base_link
        position: [ -0.29, 0.2988, 0.9232 ]
        rpy: [ -0.0035, -0.0997, 3.1357968 ]
        <<: *NORMALLY
        tolerance_linear: 0.001

  RT_SKY_ISLAND00:
    - step: "add scene of sky island"
      scene_name: "SKY_STONE_ISLAND"
    - step: "open gripper to grasp stone"
      gripper:
        <<: *OPEN_GRIPPER
    - step: "move to ready sky"
      arm:
        frame: base_link
        position: [ -0.29, 0.2988, 0.9232 ]
        rpy: [ -0.0035, -0.0997, 3.1357968 ]
        <<: *NORMALLY
        tolerance_linear: 0.001
    - step: "forward to catch stone"
      arm:
        joints: [ 0.2313, -0.33, -0.11, -0.3,0.2189, 0.002, 3.13 ]
        <<: *NORMALLY
        <<: *NORMAL_TOLERANCE

  RT_SKY_ISLAND000:
    - step: "add scene of sky island"
      scene_name: "SKY_STONE_ISLAND"
    - step: "move gimbal to toward"
      gimbal:
        <<: *WALKING_POS
    - step: "move to mid ready"
      arm:
        <<: *ARM_HOME

  ###################    READY    ####################
  READY_SKY_ISLAND0:
    - step: "ready"

  ###################    GAIN_STORE_STONE    ####################
  ###################    NORMAL    ####################
  NORMAL_GAIN_STORE_STONE0:
    - step: "gimbal"
      gimbal:
        <<: *BIG_STONE_POS
    - step: "home"
      arm:
        joints: [ 0., -0.28, -0.08, 0, 1.7748, 0., 0. ]
        <<: *QUICKLY
        <<: *NORMAL_TOLERANCE
    - step: " gripper"
      gripper:
        <<: *OPEN_GRIPPER
    - step: "home"
      arm:
        joints: [ 0., -0.22, 0.085, 0., 1.7748, 0., 0. ]
        <<: *NORMALLY
        <<: *BIGGER_TOLERANCE
    - step: "home"
      arm:
        joints: [ 0., -0.26, -0.04, 0., 1.7748, 0., 0. ]
        <<: *NORMALLY
        <<: *BIGGER_TOLERANCE
    - step: "home"
      arm:
        joints: [ 0., -0.26, -0.04, 0., 0.783, 0., 0. ]
        <<: *SLOWLY
        <<: *BIGGER_TOLERANCE
    - step: "home"
      arm:
        joints: [ 0., -0.175, 0.13, 0., 0.783, 0., 0. ]
        <<: *NORMALLY
        <<: *NORMAL_TOLERANCE

  ###################    SKY    ####################
  SKY_GAIN_STORE_STONE0:
    - step: "gimbal"
      gimbal:
        <<: *BIG_STONE_POS
    - step: "home"
      arm:
        joints: [ 0, -0.3, -0.1, 0., 0.4698, 0., 0. ]
        <<: *QUICKLY
        <<: *NORMAL_TOLERANCE
    - step: "home"
      arm:
        joints: [ 0.238, -0.34, 0.198, 0., 3.0276, 0., 0. ]
        <<: *QUICKLY
        <<: *NORMAL_TOLERANCE
    - step: "home"
      arm:
        joints: [ 0.238, -0.044, 0.198, 0., 3.0276, 0., 0. ]
        <<: *QUICKLY
        <<: *NORMAL_TOLERANCE
    - step: "home"
      gripper:
        <<: *OPEN_GRIPPER
    - step: "home"
      arm:
        joints: [ 0.18, -0.044, 0.198, 0., 3.0276, 0., 0. ]
        <<: *NORMALLY
        tolerance_joints: [ 0.018, 0.01, 0.01, 0.004, 0.4, 0.4, 0.4 ]
    - step: "home"
      arm:
        joints: [ 0.238, -0.28, 0.198, 0., 2.436, 0., 0. ]
        <<: *NORMALLY
        <<: *NORMAL_TOLERANCE
    - step: "home"
      arm:
        joints: [ 0.238, -0.34, 0.16, 0., 2.436, 0., 0. ]
        <<: *SLOWLY
        <<: *NORMAL_TOLERANCE
    - step: "home"
      arm:
        joints: [ 0.238, -0.34, 0.198, 0., 0.87, 0., 0. ]
        <<: *SLOWLY
        <<: *NORMAL_TOLERANCE

  ###################    EXCHANGE    ####################
  EXCHANGE0:
    - step: "add scene of sky island"
      scene_name: "EXCHANGE_ISLAND"
    - step: "gimbal"
      gimbal:
        <<: *BIG_STONE_POS
    - step: "down stone"
      arm:
        joints: [ 0.22, 0.092, 0.18, 0., 1.2876, 0., 0. ]
        <<: *QUICKLY
        <<: *BIGGER_TOLERANCE

  EXCHANGE00:
    - step: "add scene of sky island"
      scene_name: "EXCHANGE_ISLAND"
    - step: "close gripper"
      gripper:
        <<: *CLOSE_GRIPPER
        # wait
    - step: "push stone"
      arm:
        joints: [ 0.22, -0.1, 0.05, 0., 1.4616, 0., 0. ]
        <<: *BIGGER_TOLERANCE
        tolerance_joints: [ 0.08, 0.08, 0.08, 0.004, 0.6, 0.6, 0.6 ]
    - step: "push stone"
      arm:
        joints: [ 0.22, 0.095, 0.305, 0., 1.4616, 0., 0. ]
        <<: *QUICKLY
        <<: *BIGGER_TOLERANCE
    - step: "push stone"
      arm:
        joints: [ 0.22, 0.095, 0.305, 0., 1.15, 0., 0. ]
        <<: *QUICKLY
        <<: *BIGGER_TOLERANCE

  EXCHANGE000:
    - step: "add scene of sky island"
      scene_name: "EXCHANGE_ISLAND"
    - step: "gimbal"
      gimbal:
        <<: *WALKING_POS
    - step: "move to mid ready"
      arm:
        <<: *ARM_HOME

  ###################    GROUND_STONE    ####################
  GROUND_STONE0:
    - step: "gimbal"
      gimbal:
        <<: *WALKING_POS
    - step: "open gripper"
      gripper:
        <<: *OPEN_GRIPPER
    - step: "repeat pre"
      arm:
        joints: [ 0.2, 0.270, 0.283, 0.3, 3.14, 0., 0. ]
        <<: *QUICKLY
        tolerance_joints: [ 0.018, 0.022, 0.022, 0.009, 0.2, 0.2, 0.2 ]
    - step: "down stone"
      arm:
        joints: [ 0., 0.270, 0.284, 0.3,  3.14, 0., 0. ]
        <<: *NORMALLY
        tolerance_joints: [ 0.018, 0.022, 0.022, 0.009, 0.2, 0.2, 0.2 ]
    - step: "up stone"
      arm:
        joints: [ 0.24, 0.270, 0.284, 0.3,  3.14, 0., 0. ]
        <<: *QUICKLY
        <<: *BIGGER_TOLERANCE
    - step: "up stone"
      arm:
        joints: [ 0.24, 0.270, 0.284, 0.3, 1.044, 0., 0. ]
        <<: *SLOWLY
        <<: *BIGGER_TOLERANCE

  ###################    STORE_STONE    ####################
  STORE_STONE0:
    - step: "gimbal"
      gimbal:
        <<: *BIG_STONE_POS
    - step: "set space to stone"
      arm:
        joints: [ 0., -0.2, -0.016, 0., 0.696, 0., 0. ]
        <<: *NORMALLY
        <<: *BIGGER_TOLERANCE
    - step: "down stone"
      arm:
        joints: [ 0., -0.2, -0.07, 0., 1.7226, 0., 0. ]
        <<: *NORMALLY
        <<: *BIGGER_TOLERANCE
    - step: "open gripper"
      gripper:
        <<: *CLOSE_GRIPPER
    - step: "push stone deep"
      arm:
        joints: [ 0., -0.15, -0.016, 0., 1.7226, 0., 0. ]
        <<: *NORMALLY
        <<: *BIGGER_TOLERANCE
    - step: "push stone deep"
      arm:
        joints: [ 0., -0.2, -0.077, 0., 1.7226, 0., 0. ]
        <<: *QUICKLY
        <<: *BIGGER_TOLERANCE
    - step: "hold gripper"
      arm:
        joints: [ 0., -0.2, -0.016, 0., 0.3132, 0., 0. ]
        <<: *QUICKLY
        <<: *BIGGER_TOLERANCE
    - step: "hold gripper"
      arm:
        joints: [ 0.127, -0.12, 0.241, 0., 0.6438, 0., 0. ]
        <<: *QUICKLY
        <<: *BIGGER_TOLERANCE

  ###################    SMALL_ISLAND    ####################
  SMALL_STONE0:
    - step: "add scene of sky island"
      scene_name: "SMALL_STONE_ISLAND"
    - step: "open gripper"
      gripper:
        <<: *OPEN_GRIPPER
    - step: "down gripper"
      arm:
        joints: [ 0.235, -0.02, 0.2, 0., 1.05, 0., 0. ]
        <<: *QUICKLY
        <<: *BIGGER_TOLERANCE
    - step: "forward"
      arm:
        joints: [ 0.235, -0.02, 0.2, 0., 1.1658, 0., 0. ]
        <<: *QUICKLY
        <<: *BIGGER_TOLERANCE
    - step: "forward"
      arm:
        joints: [ 0.235, -0.02, 0.29, 0., 1.1658, 0., 0. ]
        <<: *QUICKLY
        <<: *BIGGER_TOLERANCE
    - step: "hold stone"
      arm:
        joints: [ 0.24, -0.02, 0.29, 0., 0.5046, 0., 0. ]
        <<: *QUICKLY
        <<: *BIGGER_TOLERANCE
    - step: "back"
      arm:
        joints: [ 0.235, -0.02, 0.2, 0., 0.5, 0., 0. ]
        <<: *QUICKLY
        <<: *BIGGER_TOLERANCE
