common:
  slowly: &SLOWLY
    speed: 0.0005
    accel: 0.0005
    timeout: 0.1
  quickly: &QUICKLY
    speed: 1.0
    accel: 1.0
    timeout: 2.
  hand:
    open: &HAND_OPEN
      position: -0.005
      delay: 0.1
    stone: &HAND_STONE
      position: -0.025
      delay: 0.4
    loosen: &HAND_LOOSEN
      position: -0.023
      delay: 0.3
    close: &HAND_CLOSE
      position: -0.028
      delay: 0.3
  arm:
    home: &ARM_HOME
      joints: [ 0., -2.181, 2.164, 0.0, 0.0 ]
      <<: *QUICKLY
      tolerance_angular: 0.1
    top: &ARM_TOP
      arm:
        joints: [ -2.735, -1.452, -0.133, 1.06, 0.0125 ]
        <<: *QUICKLY
        tolerance_angular: 0.1
    fold_lower: &ARM_FOLD_LOWER
      joints: [ 0.426, -2.286, -0.785, -0.191, -1.57 ]
      <<: *QUICKLY
      tolerance_angular: 0.5
    fold_upper: &ARM_FOLD_UPPER
      joints: [ 0., -2.286, 1.3439, -0.191, -1.57 ]
      <<: *QUICKLY
      tolerance_angular: 0.5
  gimbal:
    forward_lower: &GIMBAL_FORWARD_LOWER
      frame: base_link
      position: [ 0.5, -0.215, 0.4 ]
    forward_upper: &GIMBAL_FORWARD_UPPER
      frame: base_link
      position: [ 0.5, -0.215, 1.0 ]
    stone_big: &GIMBAL_STONE_BIG
      frame: base_link
      position: [ 0.64, 0., 0.5 ]

steps_list:
  TEST_BOX:
    - step: "add_island"
      scene:
        name: "TEST_BOX"
    - step: "pull_up1"
      arm:
        joints: [ 0., 0.2, 0.155, 0., 0.,0.,0. ]
        <<: *SLOWLY
        tolerance_angular: 0.5
