common:
  slowly: &SLOWLY
    speed: 0.2
    accel: 0.2
    timeout: 5.
  quickly: &QUICKLY
    speed: 1.0
    accel: 1.0
    timeout: 2.
  hand:
    open: &HAND_OPEN
      position: -0.005
      delay: 0.1
    stone: &HAND_STONE
      position: -0.025
      delay: 0.4
    loosen: &HAND_LOOSEN
      position: -0.023
      delay: 0.3
    close: &HAND_CLOSE
      position: -0.028
      delay: 0.3
  arm:
    home: &ARM_HOME
      joints: [ 0., -2.181, 2.164, 0.0, 0.0 ]
      <<: *QUICKLY
      tolerance_angular: 0.1
    top: &ARM_TOP
      arm:
        joints: [ -2.735, -1.452, -0.133, 1.06, 0.0125 ]
        <<: *QUICKLY
        tolerance_angular: 0.1
    fold_lower: &ARM_FOLD_LOWER
      joints: [ 0.426, -2.286, -0.785, -0.191, -1.57 ]
      <<: *QUICKLY
      tolerance_angular: 0.5
    fold_upper: &ARM_FOLD_UPPER
      joints: [ 0., -2.286, 1.3439, -0.191, -1.57 ]
      <<: *QUICKLY
      tolerance_angular: 0.5
  gimbal:
    forward_lower: &GIMBAL_FORWARD_LOWER
      frame: base_link
      position: [ 0.5, -0.215, 0.4 ]
    forward_upper: &GIMBAL_FORWARD_UPPER
      frame: base_link
      position: [ 0.5, -0.215, 1.0 ]
    stone_big: &GIMBAL_STONE_BIG
      frame: base_link
      position: [ 0.64, 0., 0.5 ]
steps_list:
  GIMBAL_FORWARD_LOWER:
    - step: "forward_lower"
      gimbal: *GIMBAL_FORWARD_LOWER
  GIMBAL_FORWARD_UPPER:
    - step: "forward_upper"
      gimbal: *GIMBAL_FORWARD_UPPER
  GIMBAL_STONE_BIG:
    - step: "stone_big"
      gimbal: *GIMBAL_STONE_BIG
  ARM_TEST: # ARM_TEST
    - step: "open_hand"
      hand: *HAND_OPEN
      gimbal:
        frame: link5
        position: [ 0., 0., 0.1 ]
    - step: "fold_upper"
      arm: *ARM_FOLD_UPPER
    - step: "home"
      arm:
        <<: *ARM_HOME

        <<: *SLOWLY
    - step: "fold_upper"
      arm: *ARM_FOLD_UPPER
    - step: "fold_lower"
      arm: *ARM_FOLD_LOWER
    - step: "close_hand"
      hand: *HAND_STONE
  ARM_FOLD_LOWER:
    - step: "base_link"
      arm: *ARM_FOLD_LOWER
      gimbal: *GIMBAL_FORWARD_LOWER
  ARM_FOLD_UPPER:
    - step: "fold_upper"
      arm: *ARM_FOLD_UPPER
      gimbal:
        frame: base_link
        position: [ 1.0, -0.22, 0.8 ]
  RECOVER:
    - step: "fold"
      hand: *HAND_OPEN
      arm:
        joints: [ 0., -2.2601, 1.4121, 0.9596, 0.0 ]
        <<: *SLOWLY
        tolerance_angular: 0.5
    - step: "push"
      arm:
        joints: [ 0., -0.6108, 1.710, -0.1745, 0.0 ]
        <<: *QUICKLY
        tolerance_angular: 0.5
  ################### GRASP_BIG ####################
  GRASP_BIG_PRE:
    - step: "prepare"
      arm: *ARM_FOLD_UPPER
      hand: *HAND_OPEN
      gimbal: *GIMBAL_STONE_BIG
  GRASP_BIG_PROC:
    - step: "home"
      arm: *ARM_HOME
      hand: *HAND_OPEN
    - step: "approach"
      arm:
        frame: base_link
        position: [ 0.5, 0., 0.48 ]
        rpy: [ 0., 0.18, 0. ]
        <<: *QUICKLY
        tolerance_linear: 0.001
      gimbal:
        frame: base_link
        position: [ 0.5, 0., 0.49 ]
    - step: "close_hand"
      hand: *HAND_STONE
    - step: "pull_up"
      arm:
        frame: base_link
        position: [ 0.3, 0., 0.66 ]
        rpy: [ 0., -0.7866, 0. ]
        <<: *QUICKLY
        tolerance_linear: 0.001
      gimbal:
        frame: link5
        position: [ 0., 0., 0. ]
    - step: "fold_upper"
      arm:
        joints: [ -2.65, -1.4, 1.01, 0.26, 0.0 ]
        <<: *QUICKLY
        tolerance_angular: 0.5
  GRASP_BIG_AFTER:
    - step: "fold_lower"
      arm:
        joints: [ -2.65, -0.22, 0.62, 0.26, 0.0 ]
        <<: *QUICKLY
        tolerance_angular: 0.5
    - step: "look_ahead"
      gimbal:
        frame: base_link
        position: [ 0.5, 0.18, 0.4 ]

  #################### GRASP_FLOOR ####################
  GRASP_FLOOR_PRE:
    - step: "above"
      arm:
        frame: base_link
        position: [ 0.4, 0., 0.28 ]
        rpy: [ 0., 1.17, 0. ]
        <<: *QUICKLY
        tolerance_linear: 0.001
      hand: *HAND_OPEN
      gimbal:
        frame: base_link
        position: [ 0.57, -0.02, 0.1 ]
  GRASP_FLOOR_PROC:
    - step: "approach"
      arm:
        frame: base_link
        position: [ 0.48, 0., 0.17 ]
        rpy: [ 0., 1.183, 0. ]
        <<: *QUICKLY
        tolerance_linear: 0.001
    - step: "hand_close"
      hand: *HAND_STONE
  GRASP_FLOOR_AFTER:
    - step: "fold_lower"
      arm:
        joints: [ -2.65, -0.22, 0.62, 0.26, 0.0 ]
        <<: *QUICKLY
        tolerance_angular: 0.5
    - step: "look_ahead"
      gimbal:
        frame: base_link
        position: [ 0.5, 0.18, 0.4 ]

  #################### EXCHANGE ####################
  EXCHANGE_PRE:
    - step: "fold_upper"
      arm:
        joints: [ -2.65, -1.239, 1.01, 0.26, 0.0 ]
        <<: *QUICKLY
        tolerance_angular: 0.5
    - step: "rise_up"
      arm:
        frame: base_link
        position: [ 0.24, 0., 0.62 ]
        rpy: [ 0., -0.3, 0. ]
        <<: *QUICKLY
        tolerance_linear: 0.01
      gimbal:
        frame: link5
        position: [ 0.1, 0., 0. ]
  EXCHANGE_PROC:
    - step: "open_hand"
      hand: *HAND_OPEN
      arm:
        frame: base_link
        position: [ 0.188, 0., 0.61 ]
        rpy: [ 0., -0.170, 0. ]
        <<: *QUICKLY
        tolerance_linear: 0.001
    - step: "close_hand"
      hand: *HAND_CLOSE
    - step: "push"
      arm:
        frame: base_link
        position: [ 0.227, 0., 0.571 ]
        rpy: [ 0., 0.111, 0. ]
        <<: *QUICKLY
        tolerance_linear: 0.1
        timeout: 1.5
    - step: "push"
      arm:
        joints: [ 0., -1.117, 0.541, 0.71, 0. ]
        <<: *QUICKLY
        tolerance_angular: 0.1
        timeout: 1.5
    - step: "flip"
      arm:
        joints: [ 0., -1.117, 0.541, 0.314, 0. ]
        <<: *QUICKLY
        tolerance_angular: 0.1
  EXCHANGE_AFTER:
    - step: "fold_lower"
      arm: *ARM_FOLD_LOWER
      gimbal: *GIMBAL_FORWARD_LOWER
      chassis:
        frame: base_link
        position: [ -0.3, 0. ]
        yaw: 0.0
        tolerance_linear: 0.02
        tolerance_angular: 0.01
        timeout: 2.0

  #################### DRAG ####################
  DRAG_LIGHT_BAR_PRE:
    - step: "prepare"
      hand: *HAND_OPEN
      arm:
        frame: base_link
        position: [ 0.413, 0., 0.4 ]
        rpy: [ 3.1415, 1.4225, 0. ]
        <<: *QUICKLY
        tolerance_linear: 0.01
  DRAG_LIGHT_BAR_PROC:
    - step: "insert"
      arm:
        frame: base_link
        position: [ 0.40, 0., 0.214 ]
        rpy: [ 3.1415, 1.4225, 0. ]
        <<: *SLOWLY
        tolerance_linear: 0.01
  DRAG_LIGHT_BAR_AFTER:
    - step: "close"
      arm:
        frame: base_link
        position: [ 0.40, 0., 0.214 ]
        rpy: [ 3.1415, 1.4225, 0. ]
        <<: *SLOWLY
        tolerance_linear: 0.01
      hand: *HAND_CLOSE

  #################### STORAGE ####################
  STORAGE_BIG_PROC:
    - step: "top"
      <<: *ARM_TOP
    - step: "approach"
      arm:
        frame: base_link
        position: [ 0.1217, 0.0269, 0.61 ]
        rpy: [ 0., 0., 2.672 ]
        <<: *QUICKLY
        tolerance_linear: 0.0005
    - step: "push"
      arm:
        frame: base_link
        position: [ 0.0624, 0.0567, 0.56 ]
        rpy: [ 0., 0.4838, 2.6748 ]
        <<: *SLOWLY
        tolerance_linear: 0.0005
    - step: "down"
      arm:
        frame: base_link
        position: [ -0.007, 0.09122, 0.55 ]
        rpy: [ 0., 0.48385, 2.67702 ]
        <<: *QUICKLY
        tolerance_linear: 0.001
      hand:
        <<: *HAND_LOOSEN
    - step: "hand_open"
      hand: *HAND_OPEN
    - step: "back"
      arm:
        frame: base_link
        position: [ 0.1164, 0.0294, 0.5774 ]
        rpy: [ 0., 0.2, 2.67528 ]
        <<: *QUICKLY
        tolerance_linear: 0.001
        tolerance_angular: 0.001
  STORAGE_BIG_AFTER:
    - step: "top"
      <<: *ARM_TOP
      gimbal:
        frame: base_link
        position: [ 1.0, -0.18, 0.8 ]
    - step: "base_link"
      arm: *ARM_FOLD_LOWER
      gimbal: *GIMBAL_FORWARD_LOWER

  #################### GRASP_BARRIER ####################
  GRASP_BARRIER_PRE:
    - step: "above"
      arm:
        frame: base_link
        position: [ 0.42, 0., 0.20 ]
        rpy: [ 0., 1.5707, 0. ]
        <<: *SLOWLY
        tolerance_linear: 0.001
      hand: *HAND_OPEN
      gimbal:
        frame: base_link
        position: [ 0.42, 0., 0.13 ]
  GRASP_BARRIER_PROC:
    - step: "approach"
      arm:
        frame: base_link
        position: [ 0.42, 0., 0.135 ]
        rpy: [ 0., 1.5707, 0. ]
        <<: *SLOWLY
        tolerance_linear: 0.001
    - step: "hand_close"
      hand: *HAND_STONE
    - step: "backward"
      chassis:
        frame: base_link
        position: [ -0.3, 0. ]
        yaw: 0.0
        tolerance_linear: 0.1
        tolerance_angular: 0.01
    - step: "lift"
      arm:
        joints: [ 0., -1.735, 0.475, 1.173, 0.0 ]
        <<: *SLOWLY
        tolerance_angular: 0.1
    - step: "turn"
      arm:
        joints: [ -1.638, -1.72, 0.503, 1.1965, 0.80 ]
        <<: *SLOWLY
        tolerance_angular: 0.1
  GRASP_BARRIER_AFTER:
    - step: "lift"
      arm:
        joints: [ -1.638, -1.72, 0.503, 1.1965, -1.5 ]
        speed: 0.1
        accel: 0.1
        timeout: 3.
        tolerance_angular: 0.1
  #################### GRASP_SMALL ####################
  GRASP_SMALL:
    - step: "hand_open"
      hand: *HAND_OPEN
    - step: "turn"
      arm:
        joints: [ -2.735, -1.452, -0.133, 1.06, 0.0125 ]
        <<: *QUICKLY
        tolerance_angular: 0.1
    - step: "turn"
      arm:
        frame: base_link
        position: [ 0.226, 0., 0.65 ]
        rpy: [ 0., -0.5259, 0. ]
        <<: *QUICKLY
        tolerance_linear: 0.001
        tolerance_angular: 0.001
    - step: "forward"
      chassis:
        frame: base_link
        position: [ 0.3, 0. ]
        yaw: 0.0
        tolerance_linear: 0.1
        tolerance_angular: 0.01
    - step: "approach"
      arm:
        frame: base_link
        position: [ 0.262, 0., 0.62 ]
        rpy: [ 0., 0., 0. ]
        <<: *QUICKLY
        tolerance_linear: 0.001
    - step: "close_hand"
      hand: *HAND_STONE
    - step: "rise"
      arm:
        frame: base_link
        position: [ 0.226, 0., 0.65 ]
        rpy: [ 0., -0.5259, 0. ]
        <<: *QUICKLY
        tolerance_linear: 0.01
    - step: "turn"
      arm:
        joints: [ -2.735, -1.452, -0.133, 1.06, 0.0125 ]
        <<: *QUICKLY
        tolerance_angular: 0.1
