common:
  speed:
    slowly: &SLOWLY
      speed: 0.2
      accel: 0.2
      timeout: 10
    normally: &NORMALLY
      speed: 0.5
      accel: 0.5
      timeout: 6.
    quickly: &QUICKLY
      speed: 1.
      accel: 1.
      timeout: 4.

  gripper:
    open_gripper: &OPEN_GRIPPER
      state: false
    close_gripper: &CLOSE_GRIPPER
      state: true

  tolerance:
    normal_tolerance: &NORMAL_TOLERANCE
      tolerance_joints: [ 0.009, 0.009, 0.009, 0.006, 0.1, 0.1, 0.1 ]
    bigger_tolerance: &BIGGER_TOLERANCE
      tolerance_joints: [ 0.014, 0.02, 0.02, 0.009, 0.2, 0.2, 0.2 ]

  arm:
    normal_home: &NORMAL_HOME
      joints: [ 0.012, 0., 0., 0., 0.87, 0., 0. ]
      <<: *NORMALLY
      <<: *NORMAL_TOLERANCE
    sky_home: &SKY_HOME
      joints: [ 0.155, 0., 0.195, 0., 0.87, 0., 0. ]
      <<: *NORMALLY
      <<: *NORMAL_TOLERANCE
    walking_home: &WALKING_HOME
      joints: [ 0.012, 0., 0., 0., 0.87, 0., 0. ]
      <<: *NORMALLY
      <<: *NORMAL_TOLERANCE
    store_and_walk_home: &STORE_AND_WALKING_HOME
      joints: [ 0.012, 0., 0., 0., 0.87, 0., 0. ]
      <<: *NORMALLY
      <<: *NORMAL_TOLERANCE

  gimbal:
    sky_gimbal: &SKY_POS
      frame: gimbal_base
      position: [ -0.2, -0.0008, 1 ]
    back_gimbal: &BACK_POS
      frame: gimbal_base
      position: [ -2 ,-0.1, -15 ]
    big_stone_gimbal: &BIG_STONE_POS
      frame: gimbal_base
      position: [ 2, 0.01, 0.1 ]
    walking_pos: &WALKING_POS
      frame: gimbal_base
      position: [ -2 ,0.01, -15 ]

steps_list:
  ################### COMMON STEP####################
  ################### HOME ####################
  EMPTY_HOME:
    - step: "approach"
      arm:
        <<: *NORMAL_HOME

  STORED_HOME:
    - step: "approach"
      arm:
        <<: *SKY_HOME

  WALKING_HOME:
    - step: "approach"
      arm:
        <<: *WALKING_HOME

  STORE_AND_WALKING_HOME:
    - step: "approach"
      arm:
        <<: *STORE_AND_WALKING_HOME
  ################### GIMBAL ####################
  SKY_GIMBAL:
    - step: "open gripper"
      gimbal:
        <<: *SKY_POS

  WALK_GIMBAL:
    - step: "open gripper"
      gimbal:
        <<: *WALKING_POS

  BIG_STONE_GIMBAL:
    - step: "open gripper"
      gimbal:
        <<: *BIG_STONE_POS

  BACK_GIMBAL:
    - step: "gimbal"
      gimbal:
        <<: *BACK_POS

  ################### GRIPPER ####################
  OPEN_GRIPPER:
    - step: "open gripper"
      gripper:
        <<: *OPEN_GRIPPER

  CLOSE_GRIPPER:
    - step: "close gripper"
      gripper:
        <<: *CLOSE_GRIPPER

  DELETE_SCENE:
    - step: "delete_scene"

  ################### BIG_ISLAND ####################
  ###################    READY    ####################
  READY_BIG_ISLAND0:
    - step: "add scene of sky island"
      scene_name: "BIG_STONE_ISLAND"
    - step: "gimbal"
      gimbal:
        <<: *BIG_STONE_POS
    - step: "ready"
      arm:
        joints: [ 0.238, 0.170, 0.3, 0,1.6878, 0, 0 ]
        <<: *SLOWLY
        <<: *NORMAL_TOLERANCE
  ###################    MID    ####################
  MID_BIG_ISLAND0:
    - step: "add scene of sky island"
      scene_name: "BIG_STONE_ISLAND"
    - step: "gimbal"
      gimbal:
        <<: *BIG_STONE_POS
    - step: "ready"
      arm:
        joints: [ 0.238, 0.170, 0.3, 0,1.6878, 0, 0 ]
        <<: *NORMALLY
        <<: *NORMAL_TOLERANCE

  MID_BIG_ISLAND00:
    - step: "add scene of sky island"
      scene_name: "BIG_STONE_ISLAND"
    - step: "gimbal"
      gimbal:
        <<: *BIG_STONE_POS
    - step: " gripper"
      gripper:
        <<: *OPEN_GRIPPER
    - step: "ready"
      arm:
        joints: [ 0.238, 0.185, 0.219, 0,1.6878, 0, 0 ]
        <<: *NORMALLY
        <<: *NORMAL_TOLERANCE
    - step: "ready"
      arm:
        joints: [ 0.238, 0.32, 0.3, 0,1.6878, 0, 0 ]
        <<: *NORMALLY
        <<: *BIGGER_TOLERANCE
    - step: "ready"
      arm:
        joints: [ 0.238, 0.28, 0.27, 0,1.6878, 0, 0 ]
        <<: *SLOWLY
        <<: *NORMAL_TOLERANCE
    - step: "ready"
      arm:
        joints: [ 0.238, 0.28, 0.27, 0,0.696, 0, 0 ]
        <<: *SLOWLY
        <<: *NORMAL_TOLERANCE

  MID_BIG_ISLAND000:
    - step: "add scene of sky island"
      scene_name: "BIG_STONE_ISLAND"
    - step: "gimbal"
      gimbal:
        <<: *WALKING_POS
    - step: "move to mid ready"
      arm:
        <<: *NORMAL_HOME

  ###################    LF    ####################
  LF_BIG_ISLAND0:
    - step: "add scene of sky island"
      scene_name: "BIG_STONE_ISLAND"
    - step: "gimbal"
      gimbal:
        <<: *BIG_STONE_POS
    - step: "ready"
      arm:
        joints: [ 0.238, 0.170, 0.3, 0.3,1.6878, 0, 0 ]
        <<: *NORMALLY
        <<: *NORMAL_TOLERANCE

  LF_BIG_ISLAND00:
    - step: "add scene of sky island"
      scene_name: "BIG_STONE_ISLAND"
    - step: " gripper"
      gripper:
        <<: *OPEN_GRIPPER
    - step: "gimbal"
      gimbal:
        <<: *BIG_STONE_POS
    - step: "ready"
      arm:
        joints: [ 0.238, 0.170, 0.3, 0.3,1.6878, 0, 0 ]
        <<: *NORMALLY
        <<: *NORMAL_TOLERANCE
    - step: "ready"
      arm:
        joints: [ 0.238, 0.32, 0.3, 0.3,1.6878, 0, 0 ]
        <<: *NORMALLY
        <<: *BIGGER_TOLERANCE
    - step: "ready"
      arm:
        joints: [ 0.238, 0.28, 0.27, 0.3,1.6878, 0, 0 ]
        <<: *SLOWLY
        <<: *NORMAL_TOLERANCE
    - step: "ready"
      arm:
        joints: [ 0.238, 0.28, 0.27, 0.3,0.696, 0, 0 ]
        <<: *SLOWLY
        <<: *NORMAL_TOLERANCE

  LF_BIG_ISLAND000:
    - step: "add scene of sky island"
      scene_name: "BIG_STONE_ISLAND"
    - step: "gimbal"
      gimbal:
        <<: *WALKING_POS
    - step: "move to mid ready"
      arm:
        <<: *NORMAL_HOME

  ###################    RT    ####################
  RT_BIG_ISLAND0:
    - step: "add scene of sky island"
      scene_name: "BIG_STONE_ISLAND"
    - step: "gimbal"
      gimbal:
        <<: *BIG_STONE_POS
    - step: "ready"
      arm:
        joints: [ 0.238, 0.170, 0.3, -0.3,1.6878, 0, 0 ]
        <<: *NORMALLY
        <<: *NORMAL_TOLERANCE

  RT_BIG_ISLAND00:
    - step: "add scene of sky island"
      scene_name: "BIG_STONE_ISLAND"
    - step: " gripper"
      gripper:
        <<: *OPEN_GRIPPER
    - step: "gimbal"
      gimbal:
        <<: *BIG_STONE_POS
    - step: "ready"
      arm:
        joints: [ 0.238, 0.170, 0.3, -0.3,1.6878, 0, 0 ]
        <<: *NORMALLY
        <<: *NORMAL_TOLERANCE
    - step: "ready"
      arm:
        joints: [ 0.238, 0.32, 0.3, -0.3,1.6878, 0, 0 ]
        <<: *NORMALLY
        <<: *BIGGER_TOLERANCE
    - step: "ready"
      arm:
        joints: [ 0.238, 0.28, 0.27, -0.3,1.6878, 0, 0 ]
        <<: *SLOWLY
        <<: *NORMAL_TOLERANCE
    - step: "ready"
      arm:
        joints: [ 0.238, 0.28, 0.27, -0.3,0.696, 0, 0 ]
        <<: *SLOWLY
        <<: *NORMAL_TOLERANCE

  RT_BIG_ISLAND000:
    - step: "add scene of sky island"
      scene_name: "BIG_STONE_ISLAND"
    - step: "gimbal"
      gimbal:
        <<: *WALKING_POS
    - step: "move to mid ready"
      arm:
        <<: *NORMAL_HOME

  ###################    SKY_ISLAND    ####################
  ###################    READY    ####################
  READY_SKY_ISLAND0:
    - step: "add scene of sky island"
      scene_name: "SKY_STONE_ISLAND"
    - step: "gimbal"
      gimbal:
        <<: *SKY_POS
    - step: "ready"
      arm:
        joints: [ 0.238, -0.34, -0.11, 0,0.15, 0, 3.14 ]
        <<: *SLOWLY
        <<: *NORMAL_TOLERANCE

  ###################    MID    ####################
  MID_SKY_ISLAND0:
    - step: "add scene of sky island"
      scene_name: "SKY_STONE_ISLAND"
    - step: "open gripper to grasp stone"
      gripper:
        <<: *OPEN_GRIPPER
    - step: "gimbal"
      gimbal:
        <<: *SKY_POS
    - step: "ready"
      arm:
        joints: [ 0.238, -0.34, -0.11, 0,0.15, 0, 3.14 ]
        <<: *SLOWLY
        <<: *NORMAL_TOLERANCE

  MID_SKY_ISLAND00:
    - step: "add scene of sky island"
      scene_name: "SKY_STONE_ISLAND"
    - step: "open gripper to grasp stone"
      gripper:
        <<: *OPEN_GRIPPER
    - step: "gimbal"
      gimbal:
        <<: *SKY_POS
    - step: "ready"
      arm:
        joints: [ 0.238, -0.34, -0.11, 0,0.15, 0, 3.14 ]
        <<: *SLOWLY
        <<: *NORMAL_TOLERANCE

  MID_SKY_ISLAND000:
    - step: "add scene of sky island"
      scene_name: "SKY_STONE_ISLAND"
    - step: "move gimbal to toward"
      gimbal:
        <<: *WALKING_POS
    - step: "move to mid ready"
      arm:
        <<: *NORMAL_HOME

  ###################    LF    ####################
  LF_SKY_ISLAND0:
    - step: "add scene of sky island"
      scene_name: "SKY_STONE_ISLAND"
    - step: "open gripper to grasp stone"
      gripper:
        <<: *OPEN_GRIPPER
    - step: "gimbal"
      gimbal:
        <<: *SKY_POS
    - step: "ready"
      arm:
        joints: [ 0.238, -0.34, -0.11, -0.3,0.15, 0, 3.14 ]
        <<: *SLOWLY
        <<: *NORMAL_TOLERANCE

  LF_SKY_ISLAND00:
    - step: "add scene of sky island"
      scene_name: "SKY_STONE_ISLAND"
    - step: "open gripper to grasp stone"
      gripper:
        <<: *OPEN_GRIPPER
    - step: "gimbal"
      gimbal:
        <<: *SKY_POS
    - step: "ready"
      arm:
        joints: [ 0.238, -0.34, -0.11, -0.3,0.15, 0, 3.14 ]
        <<: *SLOWLY
        <<: *NORMAL_TOLERANCE
  LF_SKY_ISLAND000:
    - step: "add scene of sky island"
      scene_name: "SKY_STONE_ISLAND"
    - step: "move gimbal to toward"
      gimbal:
        <<: *WALKING_POS
    - step: "move to mid ready"
      arm:
        <<: *NORMAL_HOME

  ###################    RT    ####################
  RT_SKY_ISLAND0:
    - step: "add scene of sky island"
      scene_name: "SKY_STONE_ISLAND"
    - step: "open gripper to grasp stone"
      gripper:
        <<: *OPEN_GRIPPER
    - step: "move gimbal toward to island"
      gimbal:
        <<: *SKY_POS
    - step: "ready"
      arm:
        joints: [ 0.238, -0.34, -0.11, 0.3,0.15, 0, 3.14 ]
        <<: *SLOWLY
        <<: *NORMAL_TOLERANCE

  RT_SKY_ISLAND00:
    - step: "add scene of sky island"
      scene_name: "SKY_STONE_ISLAND"
    - step: "open gripper to grasp stone"
      gripper:
        <<: *OPEN_GRIPPER
    - step: "move gimbal toward to island"
      gimbal:
        <<: *SKY_POS
    - step: "ready"
      arm:
        joints: [ 0.238, -0.34, -0.11, 0.3,0.15, 0, 3.14 ]
        <<: *SLOWLY
        <<: *NORMAL_TOLERANCE

  RT_SKY_ISLAND000:
    - step: "add scene of sky island"
      scene_name: "SKY_STONE_ISLAND"
    - step: "move gimbal to toward"
      gimbal:
        <<: *WALKING_POS
    - step: "move to mid ready"
      arm:
        <<: *NORMAL_HOME

  ###################    GAIN_STORE_STONE    ####################
  ###################    NORMAL    ####################
  NORMAL_GAIN_STORE_STONE0:
    - step: "gimbal"
      gimbal:
        <<: *BIG_STONE_POS
    - step: "home"
      arm:
        joints: [ 0., -0.28, -0.08, 0, 1.7748, 0., 0. ]
        <<: *QUICKLY
        <<: *NORMAL_TOLERANCE
    - step: " gripper"
      gripper:
        <<: *OPEN_GRIPPER
    - step: "home"
      arm:
        joints: [ 0., -0.22, 0.085, 0., 1.7748, 0., 0. ]
        <<: *NORMALLY
        <<: *BIGGER_TOLERANCE
    - step: "home"
      arm:
        joints: [ 0., -0.26, -0.04, 0., 1.7748, 0., 0. ]
        <<: *NORMALLY
        <<: *BIGGER_TOLERANCE

  NORMAL_GAIN_STORE_STONE00:
    - step: "home"
      arm:
        joints: [ 0., -0.26, -0.04, 0., 0.783, 0., 0. ]
        <<: *SLOWLY
        <<: *BIGGER_TOLERANCE
    - step: "home"
      arm:
        joints: [ 0., -0.175, 0.13, 0., 0.783, 0., 0. ]
        <<: *NORMALLY
        <<: *NORMAL_TOLERANCE

  ###################    SKY    ####################
  SKY_GAIN_STORE_STONE0:
    - step: "gimbal"
      gimbal:
        <<: *BIG_STONE_POS
    - step: "home"
      arm:
        joints: [ 0, -0.3, -0.1, 0., 0.4698, 0., 0. ]
        <<: *QUICKLY
        <<: *NORMAL_TOLERANCE
    - step: "home"
      arm:
        joints: [ 0.238, -0.34, 0.198, 0., 3.0276, 0., 0. ]
        <<: *QUICKLY
        <<: *NORMAL_TOLERANCE
    - step: "home"
      arm:
        joints: [ 0.238, -0.044, 0.198, 0., 3.0276, 0., 0. ]
        <<: *QUICKLY
        <<: *NORMAL_TOLERANCE
    - step: "home"
      gripper:
        <<: *OPEN_GRIPPER
    - step: "home"
      arm:
        joints: [ 0.18, -0.044, 0.198, 0., 3.0276, 0., 0. ]
        <<: *NORMALLY
        <<: *NORMAL_TOLERANCE
    - step: "home"
      arm:
        joints: [ 0.238, -0.28, 0.198, 0., 2.436, 0., 0. ]
        <<: *NORMALLY
        <<: *NORMAL_TOLERANCE
    - step: "home"
      arm:
        joints: [ 0.238, -0.34, 0.16, 0., 2.436, 0., 0. ]
        <<: *SLOWLY
        <<: *NORMAL_TOLERANCE
    - step: "home"
      arm:
        joints: [ 0.238, -0.34, 0.198, 0., 0.87, 0., 0. ]
        <<: *SLOWLY
        <<: *NORMAL_TOLERANCE

  ###################    EXCHANGE    ####################
  EXCHANGE0:
    - step: "gimbal"
      gimbal:
        <<: *BIG_STONE_POS
    - step: "down stone"
      arm:
        joints: [ 0.22, 0.092, 0.18, 0., 1.2876, 0., 0. ]
        <<: *QUICKLY
        <<: *BIGGER_TOLERANCE

  EXCHANGE00:
    - step: "close gripper"
      gripper:
        <<: *CLOSE_GRIPPER
        # wait
    - step: "push stone"
      arm:
        joints: [ 0.22, -0.1, 0.05, 0., 1.4616, 0., 0. ]
        <<: *BIGGER_TOLERANCE
        tolerance_joints: [ 0.08, 0.08, 0.08, 0.004, 0.6, 0.6, 0.6 ]
    - step: "push stone"
      arm:
        joints: [ 0.22, 0.095, 0.305, 0., 1.4616, 0., 0. ]
        <<: *QUICKLY
        <<: *BIGGER_TOLERANCE
    - step: "push stone"
      arm:
        joints: [ 0.22, 0.095, 0.305, 0., 1.15, 0., 0. ]
        <<: *QUICKLY
        <<: *BIGGER_TOLERANCE

  EXCHANGE000:
    - step: "gimbal"
      gimbal:
        <<: *WALKING_POS
    - step: "move to mid ready"
      arm:
        <<: *NORMAL_HOME

  ###################    GROUND_STONE    ####################
  ###################    LF    ####################
  LF_GROUND_STONE0:
    - step: "gimbal"
      gimbal:
        <<: *WALKING_POS
    - step: "open gripper"
      gripper:
        <<: *OPEN_GRIPPER
    - step: "repeat pre"
      arm:
        joints: [ 0.221, 0.3, 0.3, 0.3, 3.14, 0., 0. ]
        <<: *NORMALLY
        <<: *NORMAL_TOLERANCE
  LF_GROUND_STONE00:
    - step: "repeat pre"
      arm:
        joints: [ 0., 0.3, 0.3, 0.3, 3.14, 0., 0. ]
        <<: *NORMALLY
        <<: *BIGGER_TOLERANCE
    - step: "up stone"
      arm:
        joints: [ 0.2, 0.3, 0.3, 0.3, 3.14, 0., 0. ]
        <<: *NORMALLY
        <<: *NORMAL_TOLERANCE
    - step: "up stone"
      arm:
        joints: [ 0.2, 0.3, 0.3, 0.3, 0.522, 0., 0. ]
        <<: *NORMALLY
        <<: *NORMAL_TOLERANCE
  LF_GROUND_STONE000:
    - step: "move to mid ready"
      arm:
        <<: *NORMAL_HOME

  ###################    RT    ####################
  RT_GROUND_STONE0:
    - step: "gimbal"
      gimbal:
        <<: *WALKING_POS
    - step: "open gripper"
      gripper:
        <<: *OPEN_GRIPPER
    - step: "repeat pre"
      arm:
        joints: [ 0.221, 0.3, 0.3, -0.3, 3.14, 0., 0. ]
        <<: *NORMALLY
        <<: *NORMAL_TOLERANCE
  RT_GROUND_STONE00:
    - step: "repeat pre"
      arm:
        joints: [ 0., 0.3, 0.3, -0.3, 3.14, 0., 0. ]
        <<: *NORMALLY
        <<: *BIGGER_TOLERANCE
    - step: "up stone"
      arm:
        joints: [ 0.2, 0.3, 0.3, -0.3, 3.14, 0., 0. ]
        <<: *NORMALLY
        <<: *NORMAL_TOLERANCE
    - step: "up stone"
      arm:
        joints: [ 0.2, 0.3, 0.3, -0.3, 0.522, 0., 0. ]
        <<: *NORMALLY
        <<: *NORMAL_TOLERANCE
  RT_GROUND_STONE000:
    - step: "move to mid ready"
      arm:
        <<: *NORMAL_HOME
  ###################    STORE_STONE    ####################
  STORE_STONE0:
    - step: "gimbal"
      gimbal:
        <<: *BIG_STONE_POS
    - step: "open gripper"
      gripper:
        <<: *OPEN_GRIPPER
    - step: "set space to stone"
      arm:
        joints: [ 0., -0.2, -0.016, 0., 0.696, 0., 0. ]
        <<: *NORMALLY
        <<: *BIGGER_TOLERANCE
    - step: "down stone"
      arm:
        joints: [ 0., -0.2, -0.07, 0., 1.7226, 0., 0. ]
        <<: *NORMALLY
        <<: *BIGGER_TOLERANCE
    - step: "open gripper"
      gripper:
        <<: *CLOSE_GRIPPER
    - step: "push stone deep"
      arm:
        joints: [ 0., -0.15, -0.016, 0., 1.7226, 0., 0. ]
        <<: *NORMALLY
        <<: *BIGGER_TOLERANCE
    - step: "push stone deep"
      arm:
        joints: [ 0., -0.2, -0.077, 0., 1.7226, 0., 0. ]
        <<: *QUICKLY
        <<: *BIGGER_TOLERANCE
  STORE_STONE00:
    - step: "hold gripper"
      arm:
        joints: [ 0., -0.2, -0.016, 0., 0.3132, 0., 0. ]
        <<: *QUICKLY
        <<: *BIGGER_TOLERANCE
    - step: "hold gripper"
      arm:
        joints: [ 0.127, -0.12, 0.241, 0., 0.6438, 0., 0. ]
        <<: *QUICKLY
        <<: *BIGGER_TOLERANCE

  ###################    SMALL_ISLAND    ####################
  SMALL_STONE0:
    - step: "add scene of sky island"
      scene_name: "SMALL_STONE_ISLAND"
    - step: "open gripper"
      gripper:
        <<: *OPEN_GRIPPER
    - step: "down gripper"
      arm:
        joints: [ 0.235, -0.02, 0.2, 0., 1.05, 0., 0. ]
        <<: *QUICKLY
        <<: *BIGGER_TOLERANCE
    - step: "forward"
      arm:
        joints: [ 0.235, -0.02, 0.2, 0., 1.1658, 0., 0. ]
        <<: *QUICKLY
        <<: *BIGGER_TOLERANCE
    - step: "forward"
      arm:
        joints: [ 0.235, -0.02, 0.29, 0., 1.1658, 0., 0. ]
        <<: *QUICKLY
        <<: *BIGGER_TOLERANCE
    - step: "hold stone"
      arm:
        joints: [ 0.24, -0.02, 0.29, 0., 0.5046, 0., 0. ]
        <<: *QUICKLY
        <<: *BIGGER_TOLERANCE
    - step: "back"
      arm:
        joints: [ 0.235, -0.02, 0.2, 0., 0.5, 0., 0. ]
        <<: *QUICKLY
        <<: *BIGGER_TOLERANCE
