steps_list:
  raise_arm:
    - step: get_resource
      arm:
        frame: base_link
        position: [ 0.399325,-0.0104102,0.482602 ]
        rpy: [ -3.00991,1.34776,-3.04447 ]
        speed: 1.5
        time_out: 2.
  place:
    - step: chassis
      chassis:
        frame: base_link
        position: [ 2.0,2.0 ]
        yaw: 0.0
        tolerance_linear: 999.
        tolerance_angular: 999.
    - step: put_resource
      arm:
        frame: base_link
        position: [ 0.072817,0.054926,0.5318 ]
        rpy: [ -1.5707963,1.57,0.506 ]
        speed: 1.
  grasp_big_resource:
    - step: open_hand
      hand:
        joints: [ -0. ]
        time_out: 0.5
        tolerance_linear: 0.01
        tolerance_angular: 0.01
    - step: get_resource
      arm:
        frame: base_link
        position: [ 0.400592,-0.0110176,0.473142 ]
        rpy: [ -3.10097,1.08304,-3.13549 ]
        speed: 1.
        time_out: 2.
        tolerance_linear: 0.001
        tolerance_angular: 0.001
    - step: close_hand
      hand:
        joints: [ -0.029 ]
        time_out: 0.5
        tolerance_linear: 0.005
        tolerance_angular: 0.005
    - step: raise_up
      arm:
        frame: base_link
        position: [ 0.354958,0.00659916,0.541259 ]
        rpy: [ -0.0118981,1.39383,0.0157981 ]
        speed: 1.
        time_out: 2.
  #    - step: put_resource
  #      arm:
  #        frame: base_link
  #        position: [ 0.0436255,0.0480922,0.5318 ]
  #        rpy: [ 0.458569,1.51051,3.05585 ]
  #        speed: 1.
  #        time_out: 2.
  #    - step: open_hand
  #      hand:
  #        joints: [ -0. ]
  #        time_out: 0.5
  #        tolerance_linear: 0.01
  #        tolerance_angular: 0.01
  grasp_groud:
    - step: grasp
      hand:
        joints: [ 0. ]

    - step: top
      arm:
        frame: base_link
        position: [ 0.45, 0.0, 0.3 ]
        rpy: [ 0., 1.5707, 0. ]
        speed: 0.8

    - step: approach
      arm:
        frame: base_link
        position: [ 0.45, 0.0, 0.05 ]
        rpy: [ 0., 1.5707, 0.07 ]
        cartesian: true

    - step: grasp
      hand:
        joints: [ 0. ]
    - step: 3
      arm:
        frame: base_link
        position: [ 0.47, 0.0, 0.3 ]
        rpy: [ 0., 1.5707, 0. ]

    - step: 4 # number is unnecessary
      arm:
        frame: base_link
        position: [ 0.07, 0.0, 0.4 ]
        rpy: [ 0., -3.1415926, 0. ]
        speed: .2
    - step: grasp
      hand:
        joints: [ 0. ]