steps_list:
  place:
    - step: grasp
      end_effector_target:
        hand_open: after

    - step: 4 # number is unnecessary
      end_effector_target:
        frame: base_link
        position: [ 0.05, 0.0, 0.50 ]
        rpy: [ 0., -3.1415926, 0. ]
        speed: 1.

    - step: 4 # number is unnecessary
      end_effector_target:
        frame: base_link
        position: [ 0.05, 0.0, 0.41 ]
        rpy: [ 0., -3.1415926, 0. ]
        speed: 1.
        cartesian: true

    - step: grasp
      end_effector_target:
        hand_close: after

    - step: top
      joints_target:
        joints: [ 0., -1.5358, 0.1, 0.0, 0. ]

    - step: top
      joints_target:
        joints: [ 0., -1.4835, 0.3839, 0.94247, 0. ]

    - step: grasp
      end_effector_target:
        hand_open: after

    - step: top
      joints_target:
        joints: [ 0., -2.16, 1.02, 1.15, 0. ]

    - step: grasp
      end_effector_target:
        hand_close: after

    - step: top
      joints_target:
        joints: [ 0., -1.4835, 0.3839, 0.94247, -0.5 ]
  grasp_small_resource:
    - step: base_motion
      base_target:
        chassis: [ 2.0, 2.0, 0.0 ]
        gimbal: [ 0.0, 0.0 ] #[yaw,pitch]

    - step: grasp
      end_effector_target:
        hand_open: after

    - step: top
      end_effector_target:
        frame: base_link
        position: [ 0.3, 0.0, 0.5 ]
        rpy: [ 0., 0., 0. ]
        speed: 0.8
      base_target:
        chassis: [ 0.0, 0.0, 0.0 ]

    - step: top
      joints_target:
        joints: [ 0., -1.4835, 0.3839, 0.94247, 0. ]

    - step: grasp
      end_effector_target:
        hand_close: after

    - step: 4 # number is unnecessary
      end_effector_target:
        frame: base_link
        position: [ 0.07, 0.0, 0.4 ]
        rpy: [ 0., -3.1415926, 0. ]
        speed: .2

    - step: grasp
      end_effector_target:
        hand_open: after
  grasp_groud:
    - step: grasp
      end_effector_target:
        hand_open: after

    - step: top
      end_effector_target:
        frame: base_link
        position: [ 0.45, 0.0, 0.3 ]
        rpy: [ 0., 1.5707, 0. ]
        speed: 0.8

    - step: approach
      end_effector_target:
        frame: base_link
        position: [ 0.45, 0.0, 0.05 ]
        rpy: [ 0., 1.5707, 0.07 ]
        cartesian: true

    - step: grasp
      end_effector_target:
        hand_close: after

    - step: 3
      end_effector_target:
        frame: base_link
        position: [ 0.47, 0.0, 0.3 ]
        rpy: [ 0., 1.5707, 0. ]

    - step: 4 # number is unnecessary
      end_effector_target:
        frame: base_link
        position: [ 0.07, 0.0, 0.4 ]
        rpy: [ 0., -3.1415926, 0. ]
        speed: .2
    - step: grasp
      end_effector_target:
        hand_open: after
  grasp_big_resource:
    - step: grasp
      end_effector_target:
        hand_open: after

    - step: top
      end_effector_target:
        frame: base_link
        position: [ 0.3, 0.0, 0.45 ]
        rpy: [ 0., 0., 0. ]
        speed: 0.8

    - step: top
      joints_target:
        joints: [ 0., -0.50, 0., 0.68, 0. ]

    - step: grasp
      end_effector_target:
        hand_close: after

    - step: 4 # number is unnecessary
      end_effector_target:
        frame: base_link
        position: [ 0.07, 0.0, 0.4 ]
        rpy: [ 0., -3.1415926, 0. ]
        speed: .2

    - step: grasp
      end_effector_target:
        hand_open: after
