steps_list:
  0: # HAND_OPEN
    - &step_hand_open
      step: open_hand
      hand:
        joints: [ 0. ]
        speed: 1.0
        accel: 1.0
        time_out: 1.0
        tolerance_angular: 0.002
  1: # HAND_CLOSE_STONE
    - &step_hand_close_stone
      step: close_hand
      hand:
        joints: [ -0.025 ]
        speed: 1.0
        accel: 1.0
        time_out: 1.0
        tolerance_angular: 0.005
  2: # ARM_FOLD
    - &step_arm_fold
      step: arm_fold
      arm:
        joints: [ -2.87, -0.22, 0.62, 0.26, 0.0 ]
        speed: 1.0
        accel: 1.0
        time_out: 3.0
        tolerance_angular: 0.5
  5: # RECOVER
    - step: arm_home
      arm:
        joints: [ 0., -2.181, 2.164, 0.0, 0.0 ]
        speed: 0.5
        accel: 0.5
        time_out: 3.0
        tolerance_angular: 0.5
    - *step_hand_open
    - step: push
      arm:
        joints: [ 0., -0.6108, 1.710, -0.1745, 0.0 ]
        speed: 1.0
        accel: 1.0
        time_out: 2.0
        tolerance_angular: 0.8
    - step: forward
      chassis:
        frame: base_link
        position: [ 0.5, 0. ]
        yaw: 0.0
        tolerance_linear: 0.05
        tolerance_angular: 0.1
        time_out: 5.0
    - *step_hand_close_stone
    - *step_arm_fold
    - step: backward
      chassis:
        frame: base_link
        position: [ -0.5, 0. ]
        yaw: 0.0
        tolerance_linear: 0.05
        tolerance_angular: 0.1
        time_out: 5.0

  99: # TEST
    - step: home
      arm:
        frame: base_link
        position: [ 0.2, 0., 0.6 ]
        rpy: [ 0., 0., 0. ]
        speed: 0.1
        accel: 0.1
        tolerance_linear: 0.01
        tolerance_angular: 0.02
        time_out: 10.
    - step: right
      arm:
        frame: base_link
        position: [ 0.4, 0.2, 0.3 ]
        rpy: [ 0.0, 1.57, 0. ]
        speed: 0.1
        accel: 0.1
        tolerance_linear: 0.01
        tolerance_angular: 0.02
        time_out: 10.
    - step: right
      arm:
        frame: base_link
        position: [ 0.4, 0.2, 0.3 ]
        rpy: [ 0.0, 1.57, 0. ]
        speed: 0.1
        accel: 0.1
        tolerance_linear: 0.01
        tolerance_angular: 0.02
        time_out: 10.
  #    - step: right
  #      arm:
  #        frame: link1
  #        position: [ 0.1, -0.2, 0.2 ]
  #        rpy: [ 0., 1.5707963, 0. ]
  #        speed: 0.1
  #        accel: 0.1
  #        tolerance_linear: 0.01
  #        tolerance_angular: 0.02
  #        time_out: 3.
