steps_list:
  raise_arm:
    - step: get_resource
      arm:
        frame: base_link
        position: [ 0.337827,-0.0120128,0.514362 ]
        rpy: [ -2.79192,1.48283,-2.84672 ]
        speed: 1.5
        time_out: 2.
  place:
    - step: chassis
      chassis:
        frame: base_link
        position: [ 2.0,2.0 ]
        yaw: 0.0
        tolerance_linear: 999.
        tolerance_angular: 999.
    - step: put_resource
      arm:
        frame: base_link
        position: [ 0.072817,0.054926,0.5318 ]
        rpy: [ -1.5707963,1.57,0.506 ]
        speed: 1.
  grasp_big_resource:
    - step: open_hand
      hand:
        joints: [ -0. ]
        time_out: 0.5
        tolerance_linear: 0.01
        tolerance_angular: 0.01
    - step: get_resource
      arm:
        frame: base_link
        position: [ 0.337827,-0.0120128,0.514362 ]
        rpy: [ -2.79192,1.48283,-2.84672 ]
        speed: 1.5
        time_out: 2.
    - step: close_hand
      hand:
        joints: [ -0.011 ]
        time_out: 0.5
        tolerance_linear: 0.01
        tolerance_angular: 0.01
    - step: put_resource
      arm:
        frame: base_link
        position: [ 0.0436255,0.0480922,0.5318 ]
        rpy: [ 0.458569,1.51051,3.05585 ]
        speed: 1.5
        time_out: 2.
    - step: open_hand
      hand:
        joints: [ -0. ]
        time_out: 0.5
        tolerance_linear: 0.01
        tolerance_angular: 0.01
  grasp_groud:
    - step: grasp
      hand:
        joints: [ 0. ]

    - step: top
      arm:
        frame: base_link
        position: [ 0.45, 0.0, 0.3 ]
        rpy: [ 0., 1.5707, 0. ]
        speed: 0.8

    - step: approach
      arm:
        frame: base_link
        position: [ 0.45, 0.0, 0.05 ]
        rpy: [ 0., 1.5707, 0.07 ]
        cartesian: true

    - step: grasp
      hand:
        joints: [ 0. ]
    - step: 3
      arm:
        frame: base_link
        position: [ 0.47, 0.0, 0.3 ]
        rpy: [ 0., 1.5707, 0. ]

    - step: 4 # number is unnecessary
      arm:
        frame: base_link
        position: [ 0.07, 0.0, 0.4 ]
        rpy: [ 0., -3.1415926, 0. ]
        speed: .2
    - step: grasp
      hand:
        joints: [ 0. ]