common:
  slowly: &SLOWLY
    speed: 0.2
    accel: 0.2
    timeout: 5.
  quickly: &QUICKLY
    speed: 1.0
    accel: 0.7
    timeout: 2.
  hand:
    open: &HAND_OPEN
      position: -0.002
      delay: 0.1
    close: &HAND_CLOSE
      position: -0.030
      delay: 0.4
    loosen: &HAND_LOOSEN
      position: -0.024
      delay: 0.3
  arm:
    home: &ARM_HOME
      joints: [ 0., -2.181, 2.164, 0.0, 0.0 ]
      <<: *QUICKLY
      tolerance_angular: 0.1
    top: &ARM_TOP
      arm:
        joints: [ -2.735, -1.452, -0.133, 1.06, 0.0125 ]
        <<: *QUICKLY
        tolerance_angular: 0.1
    fold_lower: &ARM_FOLD_LOWER
      joints: [ -2.65, -0.22, 0.62, 0.26, 0.0 ]
      <<: *QUICKLY
      tolerance_angular: 0.5
    fold_upper: &ARM_FOLD_UPPER
      joints: [ -2.65, -1.239, 1.01, 0.26, 0.0 ]
      <<: *QUICKLY
      tolerance_angular: 0.5
  gimbal:
    forward_lower: &GIMBAL_FORWARD_LOWER
      frame: mast
      position: [ 0.5, 0., 0.5 ]
    forward_upper: &GIMBAL_FORWARD_UPPER
      frame: mast
      position: [ 0.5, 0., 1.5 ]

steps_list:
  ARM_TEST: # ARM_TEST
    - step: "open_hand"
      hand: *HAND_OPEN
      gimbal:
        frame: link5
        position: [ 0., 0., 0.1 ]
    - step: "home"
      arm:
        <<: *ARM_HOME
        <<: *SLOWLY
    - step: "fold_lower"
      arm: *ARM_FOLD_LOWER
    - step: "close_hand"
      hand: *HAND_CLOSE
  ARM_FOLD_LOWER:
    - step: "fold_lower"
      arm: *ARM_FOLD_LOWER
      gimbal:
        frame: base_link
        position: [ 0.5, 0., 0.48 ]
  ARM_FOLD_UPPER:
    - step: "fold_upper"
      arm: *ARM_FOLD_UPPER
      gimbal:
        frame: base_link
        position: [ 0.5, 0., 0.48 ]
  GRASP_BIG:
    - step: "hand_open"
      hand: *HAND_OPEN
    - step: "fold_upper"
      arm: *ARM_FOLD_UPPER
    - step: "home"
      arm: *ARM_HOME
    - step: "approach"
      arm:
        frame: base_link
        position: [ 0.5, 0., 0.48 ]
        rpy: [ 0., 0.124, 0. ]
        <<: *QUICKLY
        tolerance_linear: 0.001
      gimbal:
        frame: base_link
        position: [ 0.5, 0., 0.48 ]
    - step: "close_hand"
      hand: *HAND_CLOSE
    - step: "pull_up"
      arm:
        frame: base_link
        position: [ 0.3, 0., 0.65 ]
        rpy: [ 0., -0.7866, 0. ]
        <<: *QUICKLY
        tolerance_linear: 0.001
      gimbal:
        frame: link5
        position: [ 0., 0., 0. ]
    - step: "fold_upper"
      arm: *ARM_FOLD_UPPER

  STORAGE:
    - step: "top"
      <<: *ARM_TOP
    - step: "approach"
      arm:
        frame: base_link
        position: [ 0.1217, 0.0269, 0.61 ]
        rpy: [ 0., 0., 2.672 ]
        <<: *QUICKLY
        tolerance_linear: 0.0005
    - step: "push"
      arm:
        frame: base_link
        position: [ 0.0624, 0.0567, 0.55 ]
        rpy: [ 0., 0.4838, 2.6748 ]
        <<: *SLOWLY
        tolerance_linear: 0.0005
    - step: "down"
      arm:
        frame: base_link
        position: [ -0.007, 0.09122, 0.54 ]
        rpy: [ 0., 0.48385, 2.67702 ]
        <<: *QUICKLY
        tolerance_linear: 0.001
      hand:
        <<: *HAND_LOOSEN
    - step: "hand_open"
      hand: *HAND_OPEN
    - step: "back"
      arm:
        frame: base_link
        position: [ 0.1164, 0.0294, 0.5674 ]
        rpy: [ 0., 0.2, 2.67528 ]
        <<: *QUICKLY
        tolerance_linear: 0.001
        tolerance_angular: 0.001

  GRASP_SMALL:
    - step: "hand_open"
      hand: *HAND_OPEN
    - step: "turn"
      arm:
        joints: [ -2.735, -1.452, -0.133, 1.06, 0.0125 ]
        <<: *QUICKLY
        tolerance_angular: 0.1
    - step: "turn"
      arm:
        frame: base_link
        position: [ 0.226, 0., 0.65 ]
        rpy: [ 0., -0.5259, 0. ]
        <<: *QUICKLY
        tolerance_linear: 0.001
        tolerance_angular: 0.001
    - step: "forward"
      chassis:
        frame: base_link
        position: [ 0.3, 0. ]
        yaw: 0.0
        tolerance_linear: 0.1
        tolerance_angular: 0.01
    - step: "approach"
      arm:
        frame: base_link
        position: [ 0.262, 0., 0.62 ]
        rpy: [ 0., 0., 0. ]
        <<: *QUICKLY
        tolerance_linear: 0.001
    - step: "close_hand"
      hand: *HAND_CLOSE
    - step: "rise"
      arm:
        frame: base_link
        position: [ 0.226, 0., 0.65 ]
        rpy: [ 0., -0.5259, 0. ]
        <<: *QUICKLY
        tolerance_linear: 0.01
    - step: "turn"
      arm:
        joints: [ -2.735, -1.452, -0.133, 1.06, 0.0125 ]
        <<: *QUICKLY
        tolerance_angular: 0.1

  PLACE:
    - step: "backward"
      chassis:
        frame: base_link
        position: [ -0.3, 0. ]
        yaw: 0.0
        tolerance_linear: 0.02
        tolerance_angular: 0.01
        timeout: 2.0
    - step: "fold_upper"
      arm: *ARM_FOLD_UPPER
    - step: "rise_up"
      arm:
        frame: base_link
        position: [ 0.24, 0., 0.65 ]
        rpy: [ 0., -0.474, 0. ]
        <<: *QUICKLY
        tolerance_linear: 0.01
    - step: "forward"
      chassis:
        frame: base_link
        position: [ 0.4, 0. ]
        yaw: 0.0
        tolerance_linear: 0.10
        tolerance_angular: 0.01
        timeout: 5.0
    - step: "open_hand"
      hand: *HAND_OPEN
    - step: "backward"
      chassis:
        frame: base_link
        position: [ -0.3, 0. ]
        yaw: 0.0
        tolerance_linear: 0.1
        tolerance_angular: 0.01
        timeout: 2.0
      arm:
        frame: base_link
        position: [ 0.188, 0., 0.60 ]
        rpy: [ 0., -0.170, 0. ]
        <<: *QUICKLY
        tolerance_linear: 0.01
    - step: "close_hand"
      hand: *HAND_CLOSE
    - step: "push"
      chassis:
        frame: base_link
        position: [ 0.4, 0. ]
        yaw: 0.0
        tolerance_linear: 0.2
        tolerance_angular: 0.1
        timeout: 2.0
      arm:
        frame: base_link
        position: [ 0.35, 0., 0.62 ]
        rpy: [ 0., -0.127, 0. ]
        <<: *QUICKLY
        tolerance_linear: 0.1
    - step: "backward"
      chassis:
        frame: base_link
        position: [ -0.3, 0. ]
        yaw: 0.0
        tolerance_linear: 0.1
        timeout: 2.0
    - step: "fold_lower"
      arm: *ARM_FOLD_LOWER