common:
  slowly: &SLOWLY
    speed: 0.1
    accel: 0.1
    timeout: 5.
  quickly: &QUICKLY
    speed: 1.0
    accel: 0.7
    timeout: 2.
  hand_open: &HAND_OPEN
    force: 250
    delay: 0.1
    duration: 0.5
  hand_close: &HAND_CLOSE
    force: -400
    delay: 0.4
    duration: 2.0
  arm_home: &ARM_HOME
    joints: [ 0., -2.181, 2.164, 0.0, 0.0 ]
    <<: *QUICKLY
    tolerance_angular: 0.1
  arm_fold_lower: &ARM_FOLD_LOWER
    joints: [ -2.65, -0.22, 0.62, 0.26, 0.0 ]
    <<: *QUICKLY
    tolerance_angular: 0.5
  arm_fold_upper: &ARM_FOLD_UPPER
    joints: [ -2.65, -1.239, 1.01, 0.26, 0.0 ]
    <<: *QUICKLY
    tolerance_angular: 0.5

steps_list:
  ARM_TEST: # ARM_TEST
    - step: "open_hand"
      hand: *HAND_OPEN
    - step: "home"
      arm:
        <<: *ARM_HOME
        <<: *SLOWLY
    - step: "fold_lower"
      arm: *ARM_FOLD_LOWER
    - step: "close_hand"
      hand: *HAND_CLOSE
  ARM_FOLD_UPPER:
    - step: "fold_upper"
      arm: *ARM_FOLD_UPPER
  GRASP_BIG:
    - step: "fold_upper"
      arm: *ARM_FOLD_UPPER
    - step: "hand_open"
      hand: *HAND_OPEN
    - step: "home"
      arm: *ARM_HOME
    - step: "approach"
      arm:
        frame: base_link
        position: [ 0.5, 0., 0.48 ]
        rpy: [ 0.,0.124, 0. ]
        <<: *QUICKLY
        tolerance_linear: 0.001
        tolerance_angular: 0.0001
    - step: "close_hand"
      hand: *HAND_CLOSE
    - step: "pull_up"
      arm:
        frame: base_link
        position: [ 0.3, 0., 0.65 ]
        rpy: [ 0., -0.7866, 0. ]
        <<: *QUICKLY
        tolerance_linear: 0.001
        tolerance_angular: 0.0001
    - step: "fold_upper"
      arm: *ARM_FOLD_UPPER
    - step: "fold_lower"
      arm: *ARM_FOLD_LOWER