controller_list:
  - name: fake_engineer_arm_controller
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
  - name: fake_hand_controller
    joints:
      - right_finger_joint
initial: # Define initial robot poses.
  - group: engineer_arm
    pose: home