# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: engineer_arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - back_left_wheel_joint
    - back_right_wheel_joint
    - front_left_wheel_joint
    - front_right_wheel_joint
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - right_finger_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: engineer_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
  - name: engineer_hand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - right_finger_joint

engineer_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
  gains:
    joint1: { p: 300, i: 0.0, d: 10, i_clamp_max: 2, i_clamp_min: -2, antiwindup: true, publish_state: true }
    joint2: { p: 2000, i: 10, d: 6, i_clamp_max: 15, i_clamp_min: -15, antiwindup: true, publish_state: true }
    joint3: { p: 1000, i: 2, d: 6, i_clamp_max: 0.2, i_clamp_min: -0.2, antiwindup: true, publish_state: true }
    joint4: { p: 1, i: 0.0, d: 2, i_clamp_max: 0.2, i_clamp_min: -0.2, antiwindup: true, publish_state: true }
    joint5: { p: 1, i: 0.0, d: 2, i_clamp_max: 0.2, i_clamp_min: -0.2, antiwindup: true, publish_state: true }

engineer_hand_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - right_finger_joint
  gains:
    right_finger_joint: { p: 100000.0, i: 0.0, d: 200, i_clamp_max: 2, i_clamp_min: -2, antiwindup: true, publish_state: true }

gazebo_ros_control:
  pid_gains:
    # the following gains are used by the gazebo_mimic_joint plugin
    left_finger_joint: { p: 1000, i: 0.0, d: 100, i_clamp_max: 2, i_clamp_min: -2, antiwindup: true, publish_state: true }