# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: engineer_arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - back_left_wheel_joint
    - back_right_wheel_joint
    - front_left_wheel_joint
    - front_right_wheel_joint
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - right_finger_joint
  sim_control_mode: 1  # 0: position, 1: velocity

controller_list:
  - name: controllers/arm_trajectory_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5

controllers:
  robot_state_controller:
    type: robot_state_controller/RobotStateController
    publish_rate: 50
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  arm_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
    gains:
      joint1: { p: 300, i: 0.0, d: 10, i_clamp_max: 2, i_clamp_min: -2, antiwindup: true, publish_state: true }
      joint2: { p: 1000.0, i: 10, d: 10.0, i_clamp_max: 15, i_clamp_min: -15, antiwindup: true, publish_state: true }
      joint3: { p: 700, i: 2, d: 6, i_clamp_max: 0.2, i_clamp_min: -0.2, antiwindup: true, publish_state: true }
      joint4: { p: 105.0, i: 5.0, d: 6.5, i_clamp_max: 5, i_clamp_min: -5, antiwindup: true, publish_state: true }
      joint5: { p: 100, i: 0.0, d: 5, i_clamp_max: 2, i_clamp_min: -2, antiwindup: true, publish_state: true }
  arm_position_controller:
    type: effort_controllers/JointGroupPositionController
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
    joint1:
      pid: { p: 300, i: 0.0, d: 10 }
    joint2:
      pid: { p: 3000, i: 10, d: 10 }
    joint3:
      pid: { p: 2000, i: 2, d: 6 }
    joint4:
      pid: { p: 10, i: 0.0, d: 3.5 }
    joint5:
      pid: { p: 200, i: 0.0, d: 3.5 }
  hand_controller:
    type: effort_controllers/JointEffortController
    joint: right_finger_joint
  mast_controller:
    type: effort_controllers/JointPositionController
    joint: mast_joint
    pid: { p: 50000.0, i: 0.0, d: 1000.0 }
  rm_calibration_controllers/JointCalibrationControllercontroller:
    type: effort_controllers/JointPositionController
    joint: card_joint
    pid: { p: 10000.0, i: 0.0, d: 1000.0 }
  stone_platform_controller:
    type: effort_controllers/JointPositionController
    joint: stone_platform_joint
    pid: { p: 15000.0, i: 1000.0, d: 1000.0 }